# Generated by Django 5.1.1 on 2025-07-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundling',
            fields=[
                ('id_bundling', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bundling', models.CharField(max_length=255)),
                ('gambar_bundling', models.ImageField(upload_to='gambar_bundling/')),
                ('harga_bundling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link_bundling', models.URLField()),
                ('deskripsi_bundling', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id_kegiatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kegiatan', models.CharField(max_length=255)),
                ('gambar_kegiatan', models.ImageField(upload_to='gambar_kegiatan/')),
                ('deskripsi_kegiatan', models.TextField()),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelurahan.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('deskripsi_produk', models.TextField()),
                ('gambar_produk', models.ImageField(upload_to='gambar_produk/')),
                ('link_produk', models.URLField()),
                ('harga_produk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelurahan.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='DetailBundling',
            fields=[
                ('id_db', models.AutoField(primary_key=True, serialize=False)),
                ('kuantitas', models.IntegerField()),
                ('id_bundling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelurahan.bundling')),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelurahan.produk')),
            ],
        ),
    ]
