# Generated by Django 5.1.1 on 2025-07-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelurahan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailbundling',
            name='kuantitas',
        ),
    ]
