# Generated by Django 5.1.1 on 2025-07-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelurahan', '0002_remove_detailbundling_kuantitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundling',
            name='gambar_bundling',
            field=models.ImageField(upload_to='static/images/bundling'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='gambar_kegiatan',
            field=models.ImageField(upload_to='static/images/kegiatan'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_produk',
            field=models.ImageField(upload_to='static/images/produk'),
        ),
    ]
