# Generated by Django 5.1.1 on 2025-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelurahan', '0003_alter_bundling_gambar_bundling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='thumbnail_produk',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/thumbnails'),
        ),
    ]
