# Generated by Django 5.1.1 on 2025-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelurahan', '0004_produk_thumbnail_produk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='link_produk',
        ),
        migrations.AddField(
            model_name='produk',
            name='link_shopee',
            field=models.URLField(blank=True, null=True, verbose_name='Link Shopee'),
        ),
        migrations.AddField(
            model_name='produk',
            name='link_tokopedia',
            field=models.URLField(blank=True, null=True, verbose_name='Link Tokopedia'),
        ),
    ]
