# Generated by Django 5.1.1 on 2025-08-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelurahan', '0005_remove_produk_link_produk_produk_link_shopee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundling',
            name='link_bundling',
        ),
        migrations.AddField(
            model_name='bundling',
            name='link_shopee',
            field=models.URLField(blank=True, null=True, verbose_name='Link Shopee'),
        ),
        migrations.AddField(
            model_name='bundling',
            name='link_tokopedia',
            field=models.URLField(blank=True, null=True, verbose_name='Link Tokopedia'),
        ),
    ]
