# Generated by Django 5.1.1 on 2025-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelurahan', '0006_remove_bundling_link_bundling_bundling_link_shopee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundling',
            name='thumbnail_bundling',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/thumbnails'),
        ),
    ]
