# Generated by Django 5.1.1 on 2025-08-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelurahan', '0007_bundling_thumbnail_bundling'),
    ]

    operations = [
        migrations.CreateModel(
            name='GambarKegiatan',
            fields=[
                ('id_gambar', models.AutoField(primary_key=True, serialize=False)),
                ('gambar', models.ImageField(upload_to='static/images/kegiatan/additional/')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('id_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_tambahan', to='kelurahan.kegiatan')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
    ]
