# Generated by Django 6.0.4 on 2026-06-27 03:20

import kelurahan.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelurahan', '0008_gambarkegiatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundling',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bundling',
            name='diperbarui_pada',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='bundling',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bundling',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gambarkegiatan',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='diperbarui_pada',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='lokasi_kegiatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='tanggal_kegiatan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='diperbarui_pada',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bundling',
            name='gambar_bundling',
            field=models.ImageField(upload_to='bundling/%Y/%m/', validators=[kelurahan.validators.validate_image_size, kelurahan.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='bundling',
            name='thumbnail_bundling',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/bundling/%Y/%m/', validators=[kelurahan.validators.validate_image_size, kelurahan.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='gambarkegiatan',
            name='gambar',
            field=models.ImageField(upload_to='kegiatan/additional/%Y/%m/', validators=[kelurahan.validators.validate_image_size, kelurahan.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='gambar_kegiatan',
            field=models.ImageField(upload_to='kegiatan/%Y/%m/', validators=[kelurahan.validators.validate_image_size, kelurahan.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_produk',
            field=models.ImageField(upload_to='produk/%Y/%m/', validators=[kelurahan.validators.validate_image_size, kelurahan.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='produk',
            name='thumbnail_produk',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/produk/%Y/%m/', validators=[kelurahan.validators.validate_image_size, kelurahan.validators.validate_image_extension]),
        ),
    ]
