# Generated by Django 6.0.4 on 2026-06-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelurahan', '0009_bundling_dibuat_pada_bundling_diperbarui_pada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundling',
            name='dibuat_pada',
        ),
        migrations.RemoveField(
            model_name='bundling',
            name='diperbarui_pada',
        ),
        migrations.RemoveField(
            model_name='bundling',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bundling',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gambarkegiatan',
            name='dibuat_pada',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='dibuat_pada',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='dibuat_pada',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='diperbarui_pada',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='lokasi_kegiatan',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='tanggal_kegiatan',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='dibuat_pada',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='diperbarui_pada',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bundling',
            name='gambar_bundling',
            field=models.ImageField(upload_to='images/bundling'),
        ),
        migrations.AlterField(
            model_name='bundling',
            name='nama_bundling',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bundling',
            name='thumbnail_bundling',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
        migrations.AlterField(
            model_name='gambarkegiatan',
            name='gambar',
            field=models.ImageField(upload_to='images/kegiatan/additional/'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama_kategori',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='gambar_kegiatan',
            field=models.ImageField(upload_to='images/kegiatan'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='nama_kegiatan',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_produk',
            field=models.ImageField(upload_to='images/produk'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='nama_produk',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='thumbnail_produk',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
    ]
